version: 2.1

orbs:
  greenzie: greenzie/build_and_publish_debs@0.0.6

parameters:
  manual-bobcat-deploy:
    type: boolean
    default: false

workflows:
  version: 2
  pushbuild:
    unless: << pipeline.parameters.manual-bobcat-deploy >>
    jobs:
      # Build jobs
      - greenzie/debian_build:
          name: "amd_debian_build"
          platform: amd64
          executor: greenzie/debianize_amd64

      - greenzie/debian_build:
          name: "arm64_debian_build"
          platform: arm64
          executor: greenzie/debianize_arm64

      # Deployment jobs
      - greenzie/deploy:
          name: "deploy_amd64_greenzie"
          filters:
            branches:
              only:
                - noetic
          requires:
            - amd_debian_build

      - greenzie/deploy:
          name: "deploy_arm64_greenzie"
          architecture: arm64
          filters:
            branches:
              only:
                - noetic
          requires:
            - arm64_debian_build

      - greenzie/deploy:
          name: "deploy_all_bobcat"
          server_hostname: bobcat
          filters:
            branches:
              only:
                - noetic
          requires:
            - arm64_debian_build
            - amd_debian_build
  
  manualdeploy:
    when: << pipeline.parameters.manual-bobcat-deploy >>
    jobs:
      # Build jobs
      - greenzie/debian_build:
          name: "amd_debian_build"
          platform: amd64
          executor: greenzie/debianize_amd64

      - greenzie/debian_build:
          name: "arm64_debian_build"
          platform: arm64
          executor: greenzie/debianize_arm64

      - greenzie/deploy:
          context: GREENZIE
          name: "manual_deploy_all_bobcat"
          server_hostname: bobcat
          requires:
            - arm64_debian_build
            - amd_debian_build
